language: java
jdk:
  - openjdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script: xvfb-run mvn test -B
before_install: mvn checkstyle:check
after_script: cobertura:check

env:
  global:
    - GH_TOKEN=ddddcf8d83c4504b75a74ed873b88630a98ce22f
